import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import '../../../core/theme/theme.dart';
import '../../../shared/widgets/al_omrane_widgets.dart';
import '../../../shared/services/firestore_service.dart';
import '../../../shared/services/firebase_auth_service.dart';
import '../../../models/salle.dart';
import '../../../models/demande.dart';

class CreateDemandeScreen extends StatefulWidget {
  final Salle salle;
  final DateTime? initialDate;
  final TimeOfDay? initialStartTime;
  final TimeOfDay? initialEndTime;

  const CreateDemandeScreen({
    super.key, 
    required this.salle,
    this.initialDate,
    this.initialStartTime,
    this.initialEndTime,
  });

  @override
  State<CreateDemandeScreen> createState() => _CreateDemandeScreenState();
}

class _CreateDemandeScreenState extends State<CreateDemandeScreen> {
  final _api = FirestoreService();
  final _auth = FirebaseAuthService();

  late DateTime _selectedDate;
  late TimeOfDay _startTime;
  late TimeOfDay _endTime;
  
  final _motifController = TextEditingController();
  final _participantsController = TextEditingController(text: '1');
  bool _isSubmitting = false;
  Map<String, dynamic>? _availabilityStatus;
  bool _isValidating = false;

  @override
  void initState() {
    super.initState();
    _selectedDate = widget.initialDate ?? DateTime.now().add(const Duration(days: 1));
    _startTime = widget.initialStartTime ?? const TimeOfDay(hour: 9, minute: 0);
    _endTime = widget.initialEndTime ?? const TimeOfDay(hour: 10, minute: 0);
    _checkLiveAvailability();
  }

  Future<void> _checkLiveAvailability() async {
    setState(() => _isValidating = true);
    
    final dateStr = DateFormat('yyyy-MM-dd').format(_selectedDate);
    final startStr = '${_startTime.hour.toString().padLeft(2, '0')}:${_startTime.minute.toString().padLeft(2, '0')}';
    final endStr = '${_endTime.hour.toString().padLeft(2, '0')}:${_endTime.minute.toString().padLeft(2, '0')}';
    final participants = int.tryParse(_participantsController.text) ?? 1;

    final status = await _api.checkAvailability(
      widget.salle.id,
      dateStr,
      startStr,
      endStr,
      requestedSlots: participants,
    );

    if (mounted) {
      setState(() {
        _availabilityStatus = status;
        _isValidating = false;
      });
    }
  }

  Future<void> _selectDate() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _selectedDate,
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 90)),
      builder: (context, child) => Theme(
        data: Theme.of(context).copyWith(
          colorScheme: const ColorScheme.light(primary: AppColors.primary),
        ),
        child: child!,
      ),
    );
    if (picked != null) {
      setState(() => _selectedDate = picked);
      _checkLiveAvailability();
    }
  }

  Future<void> _selectTime(bool isStart) async {
    final picked = await showTimePicker(
      context: context,
      initialTime: isStart ? _startTime : _endTime,
    );
    if (picked != null) {
      setState(() {
        if (isStart) _startTime = picked; else _endTime = picked;
      });
      _checkLiveAvailability();
    }
  }

  Future<void> _submit() async {
    if (_motifController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Veuillez indiquer un motif')));
      return;
    }

    setState(() => _isSubmitting = true);

    final user = await _auth.getCurrentUser();
    if (user == null) return;

    final dateStr = DateFormat('yyyy-MM-dd').format(_selectedDate);
    final startStr = '${_startTime.hour.toString().padLeft(2, '0')}:${_startTime.minute.toString().padLeft(2, '0')}';
    final endStr = '${_endTime.hour.toString().padLeft(2, '0')}:${_endTime.minute.toString().padLeft(2, '0')}';
    final participants = int.tryParse(_participantsController.text) ?? 1;

    final demande = Demande(
      id: '', // Will be generated by Firestore
      userId: user.id,
      salleId: widget.salle.id,
      dateDebut: dateStr,
      dateFin: dateStr,
      heureDebut: startStr,
      heureFin: endStr,
      motif: _motifController.text,
      participantsExternes: participants,
      statut: 'en_attente',
      userName: '${user.prenom} ${user.nom}',
      salleName: widget.salle.nom,
    );

    final res = await _api.createDemande(demande);

    if (mounted) {
      setState(() => _isSubmitting = false);
      if (res['success']) {
        _showSuccess();
      } else {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(
          content: Text(res['message'] ?? 'Erreur'),
          backgroundColor: AppColors.error,
        ));
      }
    }
  }

  void _showSuccess() {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Icon(Icons.check_circle_rounded, color: AppColors.success, size: 64),
            const SizedBox(height: 16),
            Text('Demande Envoyée', style: GoogleFonts.outfit(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            const Text('Votre demande est en cours de validation par l\'administration.', textAlign: TextAlign.center),
            const SizedBox(height: 24),
            PrimaryGradientButton(
              label: 'Continuer',
              onPressed: () {
                Navigator.pop(context); // Dialog
                Navigator.pop(context); // Screen
              },
            ),
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        title: Text('Réserver ${widget.salle.nom}'),
        leading: const AlOmraneBackButton(),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildAvailabilityHeader(),
            const SizedBox(height: 32),
            Text('Détails de la réservation', style: GoogleFonts.outfit(fontSize: 18, fontWeight: FontWeight.bold, color: AppColors.onSurface)),
            const SizedBox(height: 16),
            
            _buildSelectionTile(
              label: 'Date',
              value: DateFormat('EEEE, d MMMM yyyy', 'fr_FR').format(_selectedDate),
              icon: Icons.calendar_today_rounded,
              onTap: _selectDate,
            ),
            const SizedBox(height: 16),
            Row(
              children: [
                Expanded(
                  child: _buildSelectionTile(
                    label: 'Début',
                    value: _startTime.format(context),
                    icon: Icons.access_time_rounded,
                    onTap: () => _selectTime(true),
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: _buildSelectionTile(
                    label: 'Fin',
                    value: _endTime.format(context),
                    icon: Icons.access_time_filled_rounded,
                    onTap: () => _selectTime(false),
                  ),
                ),
              ],
            ),
            
            const SizedBox(height: 24),
            _buildLabel('Nombre de participants'),
            TextField(
              controller: _participantsController,
              keyboardType: TextInputType.number,
              onChanged: (_) => _checkLiveAvailability(),
              decoration: InputDecoration(
                hintText: 'Nombre de personnes',
                prefixIcon: const Icon(Icons.people_outline_rounded, color: AppColors.primary),
                fillColor: AppColors.surface,
                filled: true,
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: BorderSide.none),
              ),
            ),

            const SizedBox(height: 24),
            _buildLabel('Motif de la réunion'),
            TextField(
              controller: _motifController,
              maxLines: 3,
              decoration: InputDecoration(
                hintText: 'Ex: Réunion de suivi de projet...',
                filled: true,
                fillColor: AppColors.surface,
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: BorderSide.none),
              ),
            ),
            
            const SizedBox(height: 40),
            PrimaryGradientButton(
              label: 'Confirmer la réservation',
              isLoading: _isSubmitting,
              onPressed: (_availabilityStatus?['available'] == true) ? _submit : null,
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildAvailabilityHeader() {
    final available = _availabilityStatus?['available'] ?? false;
    final slots = _availabilityStatus?['slots'] ?? 0;
    final total = _availabilityStatus?['capacity'] ?? widget.salle.capacite;

    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: available ? AppColors.primary.withOpacity(0.05) : AppColors.error.withOpacity(0.05),
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: available ? AppColors.primary.withOpacity(0.1) : AppColors.error.withOpacity(0.1)),
      ),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: available ? AppColors.primary : AppColors.error,
              shape: BoxShape.circle,
            ),
            child: Icon(
              available ? Icons.check_circle_outline : Icons.error_outline,
              color: Colors.white,
              size: 24,
            ),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  available ? 'Salle Disponible' : 'Salle non disponible',
                  style: GoogleFonts.outfit(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                    color: available ? AppColors.primary : AppColors.error,
                  ),
                ),
                const SizedBox(height: 2),
                _isValidating 
                  ? const SizedBox(height: 14, width: 14, child: CircularProgressIndicator(strokeWidth: 2, color: AppColors.primary))
                  : Text(
                      available 
                        ? '$slots places disponibles sur $total'
                        : 'Capacité dépassée ou créneau occupé',
                      style: GoogleFonts.inter(fontSize: 13, color: AppColors.onSurfaceVariant),
                    ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildLabel(String text) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8, left: 4),
      child: Text(text, style: GoogleFonts.inter(fontSize: 14, fontWeight: FontWeight.bold, color: AppColors.onSurfaceVariant)),
    );
  }

  Widget _buildSelectionTile({required String label, required String value, required IconData icon, required VoidCallback onTap}) {
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(16),
      child: Container(
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: Colors.grey[500]!.withOpacity(0.05),
          borderRadius: BorderRadius.circular(16),
          border: Border.all(color: Colors.grey[300]!),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(label, style: GoogleFonts.inter(fontSize: 12, color: Colors.grey[600], fontWeight: FontWeight.w600)),
            const SizedBox(height: 8),
            Row(
              children: [
                Icon(icon, size: 18, color: AppColors.primary),
                const SizedBox(width: 8),
                Text(value, style: GoogleFonts.inter(fontSize: 14, fontWeight: FontWeight.bold, color: AppColors.secondary)),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
